spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 78e3932f92dda9f54e2f
            client-secret: e4dd6eae2801a7fadfbe0f00c8f89f14447da7ee
            authorization-grant-type: authorization_code
            scope: read:user,user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          github:
            user-name-attribute: login
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            jwk-set-uri: https://api.github.com/meta/public_keys